Vet clinic database: query and update animals table
rodrigopenayo98/vet_clinic_rod pull request #2
Opened 2023-08-22 17:04 UTC by rodrigopenayo98

## Project Description for Pull Request:

In this project, I've applied advanced SQL concepts to manage a vet clinic's database. I used transactions to update and delete records while employing aggregate functions and GROUP BY clauses to answer analytical questions.

## Project Highlights:

- Added a new `species` column to the `animals` table.
- Inserted various animal records with detailed information.
- Utilized transactions to update and manage data consistently.
- Answered analytical queries using aggregate functions and GROUP BY.
- Captured key screenshots to showcase query results and transaction outcomes.

## Screenshots:

![Screenshot 1](https://drive.google.com/file/d/1x4zxgPY4gMnelgmaGjgKcoCBL9QkT8fX/view?usp=sharing)
![Screenshot 2](https://drive.google.com/file/d/1WeAsJbv-_XG7CyiNjtPp6cGag6We2hud/view?usp=sharing)
![Screenshot 3](https://drive.google.com/file/d/11_BX2g3vWBARbbtVQmferwVG4FTMfj9S/view?usp=sharing)
![Screenshot 4](https://drive.google.com/file/d/160O30AaAXj-auHM7wsB9kJ5oFf4FwO5v/view?usp=sharing)
![Screenshot 5](https://drive.google.com/file/d/1wK0bOxF86tiuDBF6iY2NudcEVKuZWHBZ/view?usp=sharing)
![Screenshot 6](https://drive.google.com/file/d/1q0Mfpt7hILe51_KXRIe3tWcdv0MsN-X9/view?usp=sharing)
![Screenshot 7](https://drive.google.com/file/d/1dBZBjOoeh0hCSNWtuCRxW5GYvQj7pdKa/view?usp=sharing)
![Screenshot 8](https://drive.google.com/file/d/1fmk9Bx-6s7jt3_5ZPOUcwrWGwklxw4Jx/view?usp=sharing)
![Screenshot 9](https://drive.google.com/file/d/1msCBvE5AA7pY8BU8r-_zTI60Ymv9ppnz/view?usp=sharing)
![Screenshot 10](https://drive.google.com/file/d/1s7hGMsiHDeI_qI1YDAMg0cbinhQvlppg/view?usp=sharing)
![Screenshot 11](https://drive.google.com/file/d/1JvcTKNdcjHhGSBPjCBX5zWM5egaGAvFh/view?usp=sharing)
![Screenshot 12](https://drive.google.com/file/d/1ipvAG7ysEd7tA14aFmq7_ab_E9hX6nkX/view?usp=sharing)
![Screenshot 13](https://drive.google.com/file/d/15SklMOf5MpUmeOyMb6QYpduCgZUcqkbl/view?usp=sharing)
![Screenshot 14](https://drive.google.com/file/d/12pU6QWUSC8DEEt0unMET0ovgX2vYQ1f-/view?usp=sharing)
![Screenshot 15](https://drive.google.com/file/d/1Rk-x-_JGkUQeEXwAdaNR-ww770uSvsQy/view?usp=sharing)
![Screenshot 16](https://drive.google.com/file/d/1o4hL_lKLk019Uxg-IUFuSl7_lnV5QakH/view?usp=sharing)
![Screenshot 17](https://drive.google.com/file/d/1U3dL5WizSqPehqWvnEDeSbnvboAocw-o/view?usp=sharing)
![Screenshot 18](https://drive.google.com/file/d/11HVUXN1x3wryqtjAnc35gCcd2RZg3Qtc/view?usp=sharing)

2023-08-22 21:31 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @rodrigopenayo98 , |
|Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! |
| <img src="https://media3.giphy.com/media/qQdL532ZANbjy/giphy.gif"/> |

## Highlights

- [ ].. ✅ Great readme file
- [ ].. ✅ Clean code

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-22 21:31 UTC, joskalenda commented on queries.sql
- [ ] You are missing the very first point of the queries, you are asked to do this as stated in the image below..., please make sure you have insert this and resubmit your work

<img width="550" alt="1" src="https://github.com/rodrigopenayo98/vet_clinic_rod/assets/77843050/6f0cc256-8084-4f02-99f0-a02abe471ff1">

2023-08-23 00:27 UTC, rodrigopenayo98 commented on queries.sql
@joskalenda  thank you for the correction! I already added the query that I was missing!

2023-08-23 00:57 UTC, mwanawabangona approved these changes
Hi @rodrigopenayo98 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations!  
![](https://camo.githubusercontent.com/d348d0cdaa16b202354d12402e048f52cd4d589b4ec0e55f07d62c2f22753376/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f373246634a6d4c7a4964594a646d44652f67697068792e676966)

## Highlights
*   No linter errors :heavy_check_mark:
*   Repo looks professional :briefcase:
*   Solid pull request scroll
*   Good quality commits
*   Good job implementing the requested changes!! :clap: :clap: :clap:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-23 14:10 UTC, merged